### ISSUE TITLE
No Records in View ListByCategories when having categories with same slug-name

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [TYPO3GmbH/blog#111]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

I have the following categories after updating from LTS 8 to LTS 9:

_ | uid_ | pid | title__ | slug
1 | 003 | 308 | Cloud | cloud
2 | 500 | 743 | Cloud | cloud
3 | 299 | 791 | Cloud | cloud
4 | 421 | 791 | Cloud | cloud
5 | 488 | 743 | Cloud | cloud (blog-category)

Only the last one is a category for our blog. The category widget shows the correct amount of records (2) with that category. Now when I click the category to list all records with that category, it shows the message "no blog entries".

I found out that other categories with the same slug-name causes this. <f:debug> shows that category "3" is set, so no blog-records are found. If I deactivate the first one, then category "500" is set -> no records either. If I deactivate categories 1-4, then the records show up. I could also rename the slugs of categories 1-4 -> records show up.

It seems like the first category with the slug "cloud" is fetched, which has of course no blog-records.

It might affect tags or authors and the like, too.

**Expected behavior:** The category based on its ID is fetched.

**Actual behavior:** The category based on its slug is fetched.

Composer Installation:
TYPO3 9.5.9
t3g/blog 9.1.2

**Comment by benjaminkott** [comment]
Slugs within a site should never have the same slug for matching record types. If you want to include the same slug for all of these records i suggest to include an unique identifier within the generated url. 

See example route configuration:
```yaml
# This route enhancer config is not final
# But you can simply include it in your site configuration:
# imports:
#  - { resource: "EXT:blog/Configuration/Routes/Multisite.yaml" }
imports:
  - { resource: "EXT:blog/Configuration/Routes/Default.yaml" }

routeEnhancers:
  AuthorPosts:
    aspects:
      author_title:
        type: PersistedPatternMapper
        tableName: tx_blog_domain_model_author
        routeFieldPattern: '^(?P<slug>.+)-(?P<uid>\d+)$'
        routeFieldName: 'slug'
        routeFieldResult: '{slug}-{uid}'
  BlogCategory:
    aspects:
      category_title:
        type: PersistedPatternMapper
        tableName: sys_category
        routeFieldPattern: '^(?P<slug>.+)-(?P<uid>\d+)$'
        routeFieldName: 'slug'
        routeFieldResult: '{slug}-{uid}'
  BlogTag:
    aspects:
      tag_title:
        type: PersistedPatternMapper
        tableName: tx_blog_domain_model_tag
        routeFieldPattern: '^(?P<slug>.+)-(?P<uid>\d+)$'
        routeFieldName: 'slug'
        routeFieldResult: '{slug}-{uid}'
```

Let me know if that works for you.
