### ISSUE TITLE
Services.yaml configuration

### ISSUE THREAD

**Issue by garbast** [TYPO3GmbH/blog#157]
Please provide a Services.yaml configuration. This would make autowiring in extending context possible.
Example for minimum file.
```
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3G\AgencyPack\Blog\:
    resource: '../Classes/*'
```
